[Content]
# Needed to prevent GDM from running gnome initial setup.
# FIXME: This (g-i-s) conflicts with our first boot config, at some point we
# should make our thing not run in favor of using g-i-s on GNOME installs, but
# g-i-s wasn't super reliable...
KernelCommandLine=gnome.initial-setup=0

Packages=
	postmarketos-ui-gnome-mobile
RemovePackages=
	gnome-software-plugin-apk
