[Distribution]
Distribution=postmarketos
Release=edge

[Build]
ToolsTree=default
History=yes
CacheDirectory=mkosi.cache
Incremental=yes
ToolsTreePackages=
	btrfs-progs

[Output]
OutputDirectory=mkosi.output
SplitArtifacts=partitions
Format=disk
ImageId=postmarketOS
ManifestFormat=json
Output=%i_%v_%a

[Content]
Bootloader=none         # we install the bootloader w/ pmOS tooling
Bootable=no             # Currently fighting with mkosi... so we'll build the ESP ourselves
Packages=
	btrfs-progs
	postmarketos-base
	postmarketos-base-systemd
	postmarketos-initramfs-duranium

[Runtime]
RuntimeTrees=./mkosi.output:/var/lib/sysupdate/testing
RuntimeSize=20G
Firmware=uefi
QemuArgs=-display gtk -device virtio-keyboard-pci -device virtio-mouse-pci -serial mon:stdio
