[Distribution]
Distribution=postmarketos
Release=edge

[Build]
ToolsTree=default
History=yes
CacheDirectory=mkosi.cache
Incremental=yes
ToolsTreePackages=
	btrfs-progs
	ukify

[Output]
OutputDirectory=mkosi.output
SplitArtifacts=partitions,uki
Format=disk
ImageId=postmarketOS
ManifestFormat=json
Output=%i_%v_%a
SectorSize=512    # For FAT/ESP, to fix u-boot sector mismatch errors

[Content]
Bootloader=systemd-boot
UnifiedKernelImages=unsigned
# Match format for other artifacts that sysupdate manages
UnifiedKernelImageFormat=%i_%v_%a
KernelModulesInitrd=no
Packages=
	btrfs-progs
	postmarketos-base
	postmarketos-base-systemd
	postmarketos-duranium
	systemd-efistub

[Runtime]
RuntimeTrees=./mkosi.output:/var/lib/sysupdate/testing
RuntimeSize=20G
Firmware=uefi
QemuArgs=-display gtk -device virtio-keyboard-pci -device virtio-mouse-pci -serial mon:stdio
