[Content]
Packages=
	postmarketos-ui-phosh

	# Include pmos-base-ui-gnome-recommended to work around:
	# https://gitlab.alpinelinux.org/alpine/apk-tools/-/issues/11133
	postmarketos-base-ui-gnome-recommended
