[UKIProfile]
Profile=
	ID=debug
	TITLE=Verbose logging

Cmdline=
	console=tty0
	ignore_log_level
	plymouth.enable=0
	rd.systemd.log_level=debug,console:info
	rd.systemd.log_target=console
	systemd.log_level=debug,console:info
	systemd.log_target=console
